### ISSUE TITLE
Issue with Redeem

### ISSUE THREAD

**Issue by muneeb-ali** [miamicoin/ui#15]
First of all, great work with the UI it makes it super easy to mine 🙌 

I discovered an issue where in redeem when it checks for mined blocks i.e., when it is running the loop for "Checking for claimable blocks... 2% (Please wait)" the calls in instrument.js:109 go in a loop until one of them fails, instead of retrying upon failure the script aborts. 

My guess is this worked fine on a small set of blocks but now that MIA has been mined over several hundred blocks, the scripts needs some tweaking to not abort but retry on failure on a call to https://stacks-node-api.mainnet.stacks.co/v2/contracts/call-read

Thanks!

**Comment by vidiabtc** [comment]
Cheers Muneeb! Yea there are definitely issues with how the redeem is currently working. I've fixed the issue you mentioned here. Looks like it has to wait just over a minute before the requests can be made again once it hits that error. Unfortunately currently you may need to wait up to a few minutes to view redeemable blocks as currently it checks every single block included in the user's mining transactions.

But ideally we shouldn't even be checking this many blocks, so this fix is only temporary. We want to exclude blocks that have already been claimed from being checked. We haven't had the time to set this up yet as we've been busy with Syvita's MIA Pool and Sypool over the past week, but I'll definitely look into adding this functionality in the next few days. When we have it working it could skip checking 100s of blocks for users that have mined a lot. 

I may also add a feature where the user can manually select a range of the blocks they want to check. (Potentially limited to a 100 block range at a time, to make sure they don't run into issues with the api).

Redeeming will become a lot easier! :)
